### ISSUE TITLE
future and parallelMap

### ISSUE THREAD

**Issue by ck37** [ljdursi/beyond-single-core-R#1]
Hello,

Looks like a nice course, have you considered incorporating the future and/or parallelMap packages? Both are a bit more extensive than the foreach or parallel packages that are commonly used.

Best,
Chris

**Comment by ljdursi** [comment]
Thanks!  I learned too late about future to have incorporated it into this material the last time I taught it, but I'll leave the issue open to remind me (or anyone else who wants to use these materials) to include it.

I should mention parallelMap too, as having a single API for several different back end parallel xApplys is certainly handy.
